image: node:12.16.1

pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - npm install -g @angular/cli@9.1.0
    - npm install
    - ng build
  artifacts:
    paths:
      - dist/javelin
  only:
    - master
    - pages
